version: 2.1
orbs:
  executors:
    b_joke_machine:
      docker:
        - image: cimg/node:14
        - image: cimg/postgres:latest
      resource_class:
        large
jobs:
  tests:
    executor:
      b_joke_machine
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
      - run: 
          - npm ci
      - save_cache:
          key: node-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
            - node_modules
            - ~/.yarn
      - run:
          - cp .circleci/.env.circleci .env
      - run:
          - npm run test
workflows:
  version: 2
  b_joke_application:
    jobs:
      tests
